import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import {Button, Stack, TextField} from '@mui/material'

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Stack gap={4} alignItems='flex-start'>
                <Button variant='contained' data-cy='test1'>TEST 1</Button>
                <button data-cy='test2'>TEST 2</button>
                <TextField label="TEST 3" variant="outlined" data-cy='test3' inputProps={{"data-cy": "test3v2"}}/>
            </Stack>
        </>
    )
}
